# Generated by Django 4.0.1 on 2022-04-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0002_alter_record_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
